# Generated by Django 3.0.4 on 2020-03-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.FloatField(default=0.0)),
                ('lvl', models.PositiveIntegerField(default=1)),
                ('strength', models.PositiveIntegerField(default=1)),
                ('agility', models.PositiveIntegerField(default=1)),
                ('intelligency', models.PositiveIntegerField(default=1)),
                ('luck', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
