# Generated by Django 3.0.4 on 2020-04-08 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200328_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=4096)),
                ('lvl', models.PositiveIntegerField()),
                ('strength', models.PositiveIntegerField(default=1)),
                ('agility', models.PositiveIntegerField(default=1)),
                ('intelligence', models.PositiveIntegerField(default=1)),
                ('luck', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=4096)),
            ],
        ),
        migrations.RenameField(
            model_name='character',
            old_name='intelligency',
            new_name='intelligence',
        ),
        migrations.RenameField(
            model_name='iteminstance',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='iteminstance',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='minLvl',
        ),
        migrations.AddField(
            model_name='character',
            name='pwd',
            field=models.CharField(default='adminpass', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='effect',
            name='e_type',
            field=models.CharField(choices=[('ps', 'poison'), ('bl', 'bleed'), ('id', 'instant_damage'), ('bf', 'baf'), ('hl', 'heal'), ('mr', 'mana_restore'), ('o', 'other')], default='ps', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='effect',
            name='target',
            field=models.CharField(choices=[('s', 'self'), ('e', 'enemy'), ('f', 'friend'), ('fp', 'friends_party'), ('ep', 'enemy_party'), ('fr', 'friends_row'), ('er', 'enemy_row'), ('fc', 'friends_column'), ('ec', 'enemy_column'), ('a', 'all_field')], default='s', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('ARMOR', (('ba', 'body_armor'), ('la', 'leg_armor'), ('bo', 'boots'), ('hm', 'helmet'), ('rg', 'ring'), ('ch', 'charm'))), ('WEAPON', (('sw', 'sword'), ('bw', 'bow'), ('ts', 'two_hand_sw'), ('st', 'staff'))), ('SECOND', (('sh', 'shield'), ('or', 'orb'), ('dg', 'dagger'), ('ar', 'arrow'))), ('us', 'usable'), ('ot', 'other'), ('rn', 'rune')], default='ot', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='rune_placeholders',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='attached_runes',
            field=models.ManyToManyField(related_name='_iteminstance_attached_runes_+', to='game.ItemInstance'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='inventory',
            field=models.CharField(choices=[('b', 'onBody'), ('c', 'chest'), ('i', 'inventory')], default='i', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='required_atr',
            field=models.CharField(choices=[('s', 'strength'), ('a', 'agility'), ('i', 'intelligence'), ('l', 'luck'), ('e', 'lvl')], default='e', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='game.Location'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=4096)),
                ('distance', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three')], default=1)),
                ('mob_only', models.BooleanField(default=False)),
                ('effects', models.ManyToManyField(to='game.Effect')),
                ('requirements', models.ManyToManyField(to='game.Requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inline', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=4096)),
                ('trigger', models.CharField(choices=[('k', 'kill'), ('v', 'visit'), ('o', 'obtain'), ('d', 'deliver')], max_length=1)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('foreign', models.PositiveIntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.QuestLine')),
            ],
        ),
        migrations.CreateModel(
            name='MobsOnLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('aggressive_percent', models.FloatField(default=0.0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Location')),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Mob')),
            ],
        ),
        migrations.CreateModel(
            name='MobDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Item')),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Mob')),
            ],
        ),
        migrations.AddField(
            model_name='mob',
            name='spells',
            field=models.ManyToManyField(to='game.Spell'),
        ),
        migrations.CreateModel(
            name='CharactersSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='game.Character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Spell')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterQuests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_count', models.PositiveIntegerField(default=None, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Character')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Quest')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='quests',
            field=models.ManyToManyField(related_name='characters_on_quest', through='game.CharacterQuests', to='game.Quest'),
        ),
    ]
