# Generated by Django 3.0.6 on 2020-05-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200408_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='exp',
            new_name='_exp',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='lvl',
            new_name='_lvl',
        ),
    ]
